services:
  dev:
    image: contour-dev
    container_name: contour-dev
    volumes:
      - ../node_modules:/app/node_modules
      - ../:/app
      - ../library/db:/db
      - ../library/files:/files

    environment:
      ORIGIN: 'http://localhost:5173'
      TZ: 'America/New_York'

    stop_signal: SIGKILL
    working_dir: /app
    command: sh -c "pnpm i && pnpm exec prisma generate && pnpm run dev --host"
    init: true
    ports:
      - 5173:5173
    tty: true
    stdin_open: true