version: '3.8'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: contour-root-password
      MYSQL_DATABASE: contour
      MYSQL_USER: contour
      MYSQL_PASSWORD: contour-password
    ports:
      - 3306:3306
    volumes:
      - ../library/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - db

  contour:
    image: 'keenanrnicholson/contour:local'
    container_name: contour
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      ORIGIN: 'http://localhost:5173'
      TZ: 'America/New_York'
      DATABASE_URL: 'mysql://contour:contour-password@db:/contour'
    ports:
      - '5173:3000'
    depends_on:
      - db