services:

  dev:
    image: contour-dev
    container_name: contour-preview
    volumes:
      - ../node_modules:/app/node_modules
      - ../:/app
      - ../library/db:/db
      - ../library/files:/files

    environment:
      ORIGIN: 'http://localhost:5173'
      TZ: 'America/New_York'
      # DATABASE_URL: 'mysql://contour:contour-password@db:/contour'

    stop_signal: SIGKILL
    working_dir: /app
    command: sh -c "pnpm i && pnpx prisma generate && pnpm run build && pnpm run preview --host"
    init: true
    ports:
      - 5173:5173
    tty: true
    stdin_open: true
    # depends_on:
    #   - db
