// GENERATED FILE - DO NOT EDIT BY HAND.
// Extracted from 2024AA Section 19.9 seam tables (library/docs/2024AA - Section 19.pdf)
// by tooling in scripts/. Regenerate rather than editing; see seam.ts for the reader.

/** Which lettered seam table governs a bid period. See `seamTableFor()`. */
export type SeamTableLetter = 'A' | 'B';

/** The four transition matrices published for each lettered table. */
export type TransitionKind = '7to7' | '8to8' | '8to7' | '7to8';

/**
 * A 28-character work-day mask. Index 0 is seven days BEFORE the seam start,
 * so index 7 is the seam start itself (always a Friday) and indices 7..20 are
 * the fourteen seam days. 'X' is a scheduled work day, '.' a day off.
 */
export type SeamPattern = string;

/** `SEAM_TABLES[letter][kind][fromLine][toLine]` -> 28-day mask. */
export const SEAM_TABLES: Record<SeamTableLetter, Record<TransitionKind, Record<number, Record<number, SeamPattern>>>> = {
	A: {
		'7to7': {
			1: {
				1: '.......XXXXXXX.......XXXXXXX',
				2: '........XXXXXXX.......XXXXXX',
				3: '.......XXXXX...XXXXX...XXXXX',
				4: '.......XXXXX...XXXXX....XXXX',
				5: '.......XXXXXX...XXXXX....XXX',
				6: '.......XXXXXX...XXXXX.....XX',
				7: '.......XXXXXX...XXXXX......X',
				8: '.......XXXXXX...XXXXX.......',
				9: '.......XXXXXX...XXXXXX......',
				10: '.......XXXXXX...XXXXXXX.....',
				11: '.......XXXXXXX...XXXXXXX....',
				12: '.......XXXXXXX....XXXXXXX...',
				13: '.......XXXXXXX.....XXXXXXX..',
				14: '.......XXXXXXX......XXXXXXX.',
			},
			2: {
				1: 'X.......XXXXXXX......XXXXXXX',
				2: 'X.......XXXXXXX.......XXXXXX',
				3: 'X........XXXXXXX.......XXXXX',
				4: 'X.......XXXXX...XXXXX...XXXX',
				5: 'X.......XXXXX...XXXXX....XXX',
				6: 'X.......XXXXX...XXXXX.....XX',
				7: 'X.......XXXXX...XXXXX......X',
				8: 'X.......XXXXX...XXXXX.......',
				9: 'X.......XXXXXX...XXXXX......',
				10: 'X........XXXXXX...XXXXX.....',
				11: 'X........XXXXXX...XXXXXX....',
				12: 'X........XXXXXX...XXXXXXX...',
				13: 'X.......XXXXXXX....XXXXXXX..',
				14: 'X........XXXXXX.....XXXXXXX.',
			},
			3: {
				1: 'XX.......XXXXXXX.....XXXXXXX',
				2: 'XX.......XXXXXXX......XXXXXX',
				3: 'XX.......XXXXXXX.......XXXXX',
				4: 'XX........XXXXXXX.......XXXX',
				5: 'XX......XXXXX...XXXXX....XXX',
				6: 'XX......XXXXX...XXXXX.....XX',
				7: 'XX......XXXXX...XXXXX......X',
				8: 'XX......XXXXX...XXXXX.......',
				9: 'XX......XXXXX...XXXXXX......',
				10: 'XX.......XXXXXX...XXXXX.....',
				11: 'XX.......XXXXXX...XXXXXX....',
				12: 'XX........XXXXX...XXXXXXX...',
				13: 'XX........XXXXX....XXXXXXX..',
				14: 'XX.......XXXXXX.....XXXXXXX.',
			},
			4: {
				1: 'XXX.......XXXXXXX....XXXXXXX',
				2: 'XXX.......XXXXXXX.....XXXXXX',
				3: 'XXX.......XXXXXXX......XXXXX',
				4: 'XXX.......XXXXXXX.......XXXX',
				5: 'XXX........XXXXXXX.......XXX',
				6: 'XXX.....XXXXX...XXXXX.....XX',
				7: 'XXX.....XXXXX...XXXXX......X',
				8: 'XXX.....XXXXX...XXXXX.......',
				9: 'XXX.....XXXXX...XXXXXX......',
				10: 'XXX.......XXXXX...XXXXX.....',
				11: 'XXX.......XXXXX...XXXXXX....',
				12: 'XXX.......XXXXX...XXXXXXX...',
				13: 'XXX.......XXXXX....XXXXXXX..',
				14: 'XXX.......XXXXXX....XXXXXXX.',
			},
			5: {
				1: 'XXXX......XXXXXXX....XXXXXXX',
				2: 'XXXX.......XXXXXXX....XXXXXX',
				3: 'XXXX.......XXXXXXX.....XXXXX',
				4: 'XXXX.......XXXXXXX......XXXX',
				5: 'XXXX.......XXXXXXX.......XXX',
				6: 'XXXX....XXXXX...XXXXX.....XX',
				7: 'XXXX....XXXXX...XXXXX......X',
				8: 'XXXX....XXXXX...XXXXX.......',
				9: 'XXXX....XXXXX...XXXXXX......',
				10: 'XXXX....XXXXX...XXXXXXX.....',
				11: 'XXXX......XXXXX...XXXXXX....',
				12: 'XXXX......XXXXX...XXXXXXX...',
				13: 'XXXX.......XXXXX...XXXXXXX..',
				14: 'XXXX.......XXXXXX...XXXXXXX.',
			},
			6: {
				1: 'XXXXX.....XXXXXXX....XXXXXXX',
				2: 'XXXXX......XXXXXXX....XXXXXX',
				3: 'XXXXX......XXXXXXX.....XXXXX',
				4: 'XXXXX......XXXXXXX......XXXX',
				5: 'XXXXX......XXXXXXX.......XXX',
				6: 'XXXXX.......XXXXXXX.......XX',
				7: 'XXXXX.......XXXXXXX........X',
				8: 'XXXXX...XXXXX...XXXXX.......',
				9: 'XXXXX....XXXXX...XXXXX......',
				10: 'XXXXX.....XXXXX...XXXXX.....',
				11: 'XXXXX.....XXXXX...XXXXXX....',
				12: 'XXXXX.....XXXXX...XXXXXXX...',
				13: 'XXXXX......XXXXX...XXXXXXX..',
				14: 'XXXXX......XXXXXX...XXXXXXX.',
			},
			7: {
				1: 'XXXXXX....XXXXXXX....XXXXXXX',
				2: 'XXXXXX.....XXXXXXX....XXXXXX',
				3: 'XXXXXX.....XXXXXXX.....XXXXX',
				4: 'XXXXXX.....XXXXXXX......XXXX',
				5: 'XXXXXX.....XXXXXXX.......XXX',
				6: 'XXXXXX......XXXXXXX.......XX',
				7: 'XXXXXX.......XXXXXXX.......X',
				8: 'XXXXXX.......XXXXXXX........',
				9: 'XXXXXX...XXXXX...XXXXX......',
				10: 'XXXXXX....XXXXX...XXXXX.....',
				11: 'XXXXXX....XXXXX...XXXXXX....',
				12: 'XXXXXX....XXXXX...XXXXXXX...',
				13: 'XXXXXX.....XXXXX...XXXXXXX..',
				14: 'XXXXXX.....XXXXXX...XXXXXXX.',
			},
			8: {
				1: 'XXXXXXX....XXXXXXX...XXXXXXX',
				2: 'XXXXXXX....XXXXXXX....XXXXXX',
				3: 'XXXXXXX....XXXXXXX.....XXXXX',
				4: 'XXXXXXX....XXXXXXX......XXXX',
				5: 'XXXXXXX....XXXXXXX.......XXX',
				6: 'XXXXXXX.....XXXXXXX.......XX',
				7: 'XXXXXXX......XXXXXXX.......X',
				8: 'XXXXXXX.......XXXXXXX.......',
				9: 'XXXXXXX........XXXXXXX......',
				10: 'XXXXXXX...XXXXX...XXXXX.....',
				11: 'XXXXXXX...XXXXX...XXXXXX....',
				12: 'XXXXXXX...XXXXX...XXXXXXX...',
				13: 'XXXXXXX....XXXXX...XXXXXXX..',
				14: 'XXXXXXX....XXXXXX...XXXXXXX.',
			},
			9: {
				1: '.XXXXXXX...XXXXXXX...XXXXXXX',
				2: '.XXXXXXX...XXXXXXX....XXXXXX',
				3: '.XXXXXXX...XXXXXXX.....XXXXX',
				4: '.XXXXXXX...XXXXXXX......XXXX',
				5: '.XXXXXXX...XXXXXXX.......XXX',
				6: '.XXXXXXX....XXXXXXX.......XX',
				7: '.XXXXXXX.....XXXXXXX.......X',
				8: '.XXXXXXX......XXXXXXX.......',
				9: '.XXXXXXX.......XXXXXXX......',
				10: '.XXXXXX...XXXXX...XXXXX.....',
				11: '.XXXXXXX...XXXXX...XXXXX....',
				12: '.XXXXXXX...XXXXX...XXXXXX...',
				13: '.XXXXXXX...XXXXX...XXXXXXX..',
				14: '.XXXXXXX....XXXXX...XXXXXXX.',
			},
			10: {
				1: '..XXXXXXX...XXXXXX...XXXXXXX',
				2: '..XXXXXXX...XXXXXX....XXXXXX',
				3: '..XXXXXXX...XXXXXX.....XXXXX',
				4: '..XXXXXXX...XXXXXX......XXXX',
				5: '..XXXXXXX...XXXXXX.......XXX',
				6: '..XXXXXXX...XXXXXXX.......XX',
				7: '..XXXXXXX....XXXXXXX.......X',
				8: '..XXXXXXX.....XXXXXXX.......',
				9: '..XXXXXXX......XXXXXXX......',
				10: '..XXXXXXX.......XXXXXXX.....',
				11: '..XXXXXX...XXXXX...XXXXX....',
				12: '..XXXXXXX...XXXXX...XXXXX...',
				13: '..XXXXXXX...XXXXX...XXXXXX..',
				14: '..XXXXXXX...XXXXX...XXXXXXX.',
			},
			11: {
				1: '...XXXXXXX...XXXXX...XXXXXXX',
				2: '...XXXXXXX...XXXXX....XXXXXX',
				3: '...XXXXXXX...XXXXX.....XXXXX',
				4: '...XXXXXXX...XXXXX......XXXX',
				5: '...XXXXXXX...XXXXX.......XXX',
				6: '...XXXXXXX....XXXXX.......XX',
				7: '...XXXXXXX....XXXXXX.......X',
				8: '...XXXXXXX....XXXXXXX.......',
				9: '...XXXXXXX.....XXXXXXX......',
				10: '...XXXXXXX......XXXXXXX.....',
				11: '...XXXXXXX.......XXXXXXX....',
				12: '...XXXXXX...XXXXX...XXXXX...',
				13: '...XXXXXXX...XXXXX...XXXXX..',
				14: '...XXXXXXX...XXXXX...XXXXXX.',
			},
			12: {
				1: '....XXXXXX...XXXXX...XXXXXXX',
				2: '....XXXXXXX...XXXXX...XXXXXX',
				3: '....XXXXXXX...XXXXX....XXXXX',
				4: '....XXXXXXX...XXXXX.....XXXX',
				5: '....XXXXXXX...XXXXX......XXX',
				6: '....XXXXXXX...XXXXX.......XX',
				7: '....XXXXXXX...XXXXXX.......X',
				8: '....XXXXXXX...XXXXXXX.......',
				9: '....XXXXXXX....XXXXXXX......',
				10: '....XXXXXXX.....XXXXXXX.....',
				11: '....XXXXXXX......XXXXXXX....',
				12: '....XXXXXXX.......XXXXXXX...',
				13: '....XXXXXX...XXXXX...XXXXX..',
				14: '....XXXXXX...XXXXX...XXXXXX.',
			},
			13: {
				1: '.....XXXXX...XXXXX...XXXXXXX',
				2: '.....XXXXXX...XXXXX...XXXXXX',
				3: '.....XXXXXX...XXXXX....XXXXX',
				4: '.....XXXXXX...XXXXX.....XXXX',
				5: '.....XXXXXX...XXXXX......XXX',
				6: '.....XXXXXX...XXXXX.......XX',
				7: '.....XXXXXX...XXXXXX.......X',
				8: '.....XXXXXX...XXXXXXX.......',
				9: '.....XXXXXXX...XXXXXXX......',
				10: '.....XXXXXXX....XXXXXXX.....',
				11: '.....XXXXXXX.....XXXXXXX....',
				12: '.....XXXXXXX......XXXXXXX...',
				13: '.....XXXXXXX.......XXXXXXX..',
				14: '.....XXXXX...XXXXX...XXXXXX.',
			},
			14: {
				1: '......XXXXXXX........XXXXXXX',
				2: '......XXXXX...XXXXX...XXXXXX',
				3: '......XXXXX...XXXXX....XXXXX',
				4: '......XXXXX...XXXXX.....XXXX',
				5: '......XXXXX...XXXXX......XXX',
				6: '......XXXXX...XXXXX.......XX',
				7: '......XXXXX...XXXXXX.......X',
				8: '......XXXXX...XXXXXXX.......',
				9: '......XXXXXX...XXXXXXX......',
				10: '......XXXXXXX...XXXXXXX.....',
				11: '......XXXXXXX....XXXXXXX....',
				12: '......XXXXXXX.....XXXXXXX...',
				13: '......XXXXXXX......XXXXXXX..',
				14: '......XXXXXXX.......XXXXXXX.',
			},
		},
		'8to8': {
			2: {
				2: 'XX......XXXXXXXX......XXXXXX',
				4: 'XX.....XXXXXX...XXXXX...XXXX',
				6: 'XX.....XXXXXX...XXXXX.....XX',
				9: 'XX.....XXXXXXX...XXXXXX.....',
				11: 'XX......XXXXXXX...XXXXXXX...',
				13: 'XX.....XXXXXXXX....XXXXXXXX.',
			},
			4: {
				2: 'XXXX......XXXXXXXX....XXXXXX',
				4: 'XXXX......XXXXXXXX......XXXX',
				6: 'XXXX....XXXXX...XXXXX.....XX',
				9: 'XXXX....XXXXX...XXXXXXX.....',
				11: 'XXXX......XXXXX...XXXXXXX...',
				13: 'XXXX......XXXXX....XXXXXXXX.',
			},
			6: {
				2: 'XXXXXX.....XXXXXXXX...XXXXXX',
				4: 'XXXXXX.....XXXXXXXX.....XXXX',
				6: 'XXXXXX......XXXXXXXX......XX',
				9: 'XXXXXX...XXXXX...XXXXXX.....',
				11: 'XXXXXX...XXXXXX...XXXXXXX...',
				13: 'XXXXXX....XXXXXX...XXXXXXXX.',
			},
			9: {
				2: '.XXXXXXX...XXXXXXX....XXXXXX',
				4: '.XXXXXXX...XXXXXXXX.....XXXX',
				6: '.XXXXXXX....XXXXXXXX......XX',
				9: '.XXXXXXXX......XXXXXXXX.....',
				11: '.XXXXXXX...XXXXX...XXXXXX...',
				13: '.XXXXXXX...XXXXX...XXXXXXXX.',
			},
			11: {
				2: '...XXXXXXX...XXXXX....XXXXXX',
				4: '...XXXXXXX...XXXXX......XXXX',
				6: '...XXXXXXXX...XXXXX.......XX',
				9: '...XXXXXXXX....XXXXXXXX.....',
				11: '...XXXXXXXX......XXXXXXXX...',
				13: '...XXXXXXX...XXXXX...XXXXXX.',
			},
			13: {
				2: '.....XXXXXX...XXXXX...XXXXXX',
				4: '.....XXXXXX...XXXXXX....XXXX',
				6: '.....XXXXXX...XXXXXX......XX',
				9: '.....XXXXXXX...XXXXXXXX.....',
				11: '.....XXXXXXXX....XXXXXXXX...',
				13: '.....XXXXXXXX......XXXXXXXX.',
			},
		},
		'8to7': {
			2: {
				1: 'XX......XXXXXXXX.....XXXXXXX',
				2: 'XX......XXXXXXXX......XXXXXX',
				3: 'XX.......XXXXXXXX......XXXXX',
				4: 'XX.....XXXXXX...XXXXX...XXXX',
				5: 'XX.....XXXXXX...XXXXX....XXX',
				6: 'XX.....XXXXXX...XXXXX.....XX',
				7: 'XX.....XXXXXX...XXXXX......X',
				8: 'XX.....XXXXXX...XXXXX.......',
				9: 'XX.....XXXXXXX...XXXXX......',
				10: 'XX......XXXXXXX...XXXXX.....',
				11: 'XX......XXXXXXX...XXXXXX....',
				12: 'XX......XXXXXXX...XXXXXXX...',
				13: 'XX......XXXXXXXX...XXXXXXX..',
				14: 'XX.......XXXXXXX....XXXXXXX.',
			},
			4: {
				1: 'XXXX......XXXXXXXX...XXXXXXX',
				2: 'XXXX......XXXXXXXX....XXXXXX',
				3: 'XXXX......XXXXXXXX.....XXXXX',
				4: 'XXXX......XXXXXXXX......XXXX',
				5: 'XXXX.......XXXXXXXX......XXX',
				6: 'XXXX....XXXXX...XXXXX.....XX',
				7: 'XXXX....XXXXX...XXXXX......X',
				8: 'XXXX....XXXXX...XXXXX.......',
				9: 'XXXX....XXXXX...XXXXXX......',
				10: 'XXXX......XXXXX...XXXXX.....',
				11: 'XXXX......XXXXX...XXXXXX....',
				12: 'XXXX......XXXXX...XXXXXXX...',
				13: 'XXXX......XXXXX....XXXXXXX..',
				14: 'XXXX......XXXXXX....XXXXXXX.',
			},
			6: {
				1: 'XXXXXX....XXXXXXXX...XXXXXXX',
				2: 'XXXXXX.....XXXXXXXX...XXXXXX',
				3: 'XXXXXX.....XXXXXXXX....XXXXX',
				4: 'XXXXXX.....XXXXXXXX.....XXXX',
				5: 'XXXXXX.....XXXXXXXX......XXX',
				6: 'XXXXXX......XXXXXXXX......XX',
				7: 'XXXXXX......XXXXXXXX.......X',
				8: 'XXXXXX...XXXX...XXXXX.......',
				9: 'XXXXXX...XXXXX...XXXXX......',
				10: 'XXXXXX...XXXXXX...XXXXX.....',
				11: 'XXXXXX...XXXXXX...XXXXXX....',
				12: 'XXXXXX...XXXXXX...XXXXXXX...',
				13: 'XXXXXX....XXXXXX...XXXXXXX..',
				14: 'XXXXXX....XXXXXXX...XXXXXXX.',
			},
			9: {
				1: '.XXXXXXX...XXXXXXX...XXXXXXX',
				2: '.XXXXXXX...XXXXXXX....XXXXXX',
				3: '.XXXXXXX...XXXXXXX.....XXXXX',
				4: '.XXXXXXX...XXXXXXX......XXXX',
				5: '.XXXXXXX...XXXXXXXX......XXX',
				6: '.XXXXXXX....XXXXXXXX......XX',
				7: '.XXXXXXX.....XXXXXXXX......X',
				8: '.XXXXXXXX.....XXXXXXX.......',
				9: '.XXXXXXXX......XXXXXXX......',
				10: '.XXXXXX...XXXXX...XXXXX.....',
				11: '.XXXXXXX...XXXXX...XXXXX....',
				12: '.XXXXXXX...XXXXX...XXXXXX...',
				13: '.XXXXXXX...XXXXX...XXXXXXX..',
				14: '.XXXXXXXX...XXXXX...XXXXXXX.',
			},
			11: {
				1: '...XXXXXXX...XXXXX...XXXXXXX',
				2: '...XXXXXXX...XXXXX....XXXXXX',
				3: '...XXXXXXX...XXXXX.....XXXXX',
				4: '...XXXXXXX...XXXXX......XXXX',
				5: '...XXXXXXX...XXXXX.......XXX',
				6: '...XXXXXXXX...XXXXX.......XX',
				7: '...XXXXXXXX...XXXXXX.......X',
				8: '...XXXXXXXX...XXXXXXX.......',
				9: '...XXXXXXXX....XXXXXXX......',
				10: '...XXXXXXXX.....XXXXXXX.....',
				11: '...XXXXXXXX......XXXXXXX....',
				12: '...XXXXXX...XXXXX...XXXXX...',
				13: '...XXXXXXX...XXXXX...XXXXX..',
				14: '...XXXXXXX...XXXXX...XXXXXX.',
			},
			13: {
				1: '.....XXXXX...XXXXX...XXXXXXX',
				2: '.....XXXXXX...XXXXX...XXXXXX',
				3: '.....XXXXXX...XXXXXX...XXXXX',
				4: '.....XXXXXX...XXXXXX....XXXX',
				5: '.....XXXXXX...XXXXXX.....XXX',
				6: '.....XXXXXX...XXXXXX......XX',
				7: '.....XXXXXX...XXXXXXX......X',
				8: '.....XXXXXX...XXXXXXX.......',
				9: '.....XXXXXXX...XXXXXXX......',
				10: '.....XXXXXXXX...XXXXXXX.....',
				11: '.....XXXXXXXX....XXXXXXX....',
				12: '.....XXXXXXXX.....XXXXXXX...',
				13: '.....XXXXXXXX......XXXXXXX..',
				14: '.....XXXXX...XXXXX...XXXXXX.',
			},
		},
		'7to8': {
			1: {
				2: '........XXXXXXX.......XXXXXX',
				4: '.......XXXXX...XXXXX....XXXX',
				6: '.......XXXXXX...XXXXX.....XX',
				9: '.......XXXXXX...XXXXXXX.....',
				11: '.......XXXXXXX...XXXXXXXX...',
				13: '.......XXXXXXX.....XXXXXXXX.',
			},
			2: {
				2: 'X.......XXXXXXX.......XXXXXX',
				4: 'X.......XXXXX...XXXXX...XXXX',
				6: 'X.......XXXXX...XXXXX.....XX',
				9: 'X.......XXXXXX...XXXXXX.....',
				11: 'X........XXXXXX...XXXXXXX...',
				13: 'X.......XXXXXXX....XXXXXXXX.',
			},
			3: {
				2: 'XX.......XXXXXXX......XXXXXX',
				4: 'XX........XXXXXXX.......XXXX',
				6: 'XX......XXXXX...XXXXX.....XX',
				9: 'XX......XXXXX...XXXXXXX.....',
				11: 'XX.......XXXXXX...XXXXXXX...',
				13: 'XX........XXXXX....XXXXXXXX.',
			},
			4: {
				2: 'XXX.......XXXXXXX.....XXXXXX',
				4: 'XXX.......XXXXXXX.......XXXX',
				6: 'XXX.....XXXXX...XXXXX.....XX',
				9: 'XXX.....XXXXX...XXXXXXX.....',
				11: 'XXX.......XXXXX...XXXXXXX...',
				13: 'XXX.......XXXXX....XXXXXXXX.',
			},
			5: {
				2: 'XXXX.......XXXXXXX....XXXXXX',
				4: 'XXXX.......XXXXXXX......XXXX',
				6: 'XXXX....XXXXX...XXXXX.....XX',
				9: 'XXXX....XXXXX...XXXXXXX.....',
				11: 'XXXX......XXXXX...XXXXXXX...',
				13: 'XXXX.......XXXXX...XXXXXXXX.',
			},
			6: {
				2: 'XXXXX......XXXXXXX....XXXXXX',
				4: 'XXXXX......XXXXXXX......XXXX',
				6: 'XXXXX.......XXXXXXX.......XX',
				9: 'XXXXX....XXXXX...XXXXXX.....',
				11: 'XXXXX.....XXXXX...XXXXXXX...',
				13: 'XXXXX......XXXXX...XXXXXXXX.',
			},
			7: {
				2: 'XXXXXX.....XXXXXXX....XXXXXX',
				4: 'XXXXXX.....XXXXXXX......XXXX',
				6: 'XXXXXX......XXXXXXX.......XX',
				9: 'XXXXXX...XXXXX...XXXXXX.....',
				11: 'XXXXXX....XXXXX...XXXXXXX...',
				13: 'XXXXXX.....XXXXX...XXXXXXXX.',
			},
			8: {
				2: 'XXXXXXX....XXXXXXX....XXXXXX',
				4: 'XXXXXXX....XXXXXXX......XXXX',
				6: 'XXXXXXX.....XXXXXXX.......XX',
				9: 'XXXXXXX........XXXXXXXX.....',
				11: 'XXXXXXX...XXXXX...XXXXXXX...',
				13: 'XXXXXXX....XXXXX...XXXXXXXX.',
			},
			9: {
				2: '.XXXXXXX...XXXXXXX....XXXXXX',
				4: '.XXXXXXX...XXXXXXX......XXXX',
				6: '.XXXXXXX....XXXXXXX.......XX',
				9: '.XXXXXXX.......XXXXXXXX.....',
				11: '.XXXXXXX...XXXXX...XXXXXX...',
				13: '.XXXXXXX...XXXXX...XXXXXXXX.',
			},
			10: {
				2: '..XXXXXXX...XXXXXX....XXXXXX',
				4: '..XXXXXXX...XXXXXX......XXXX',
				6: '..XXXXXXX...XXXXXXX.......XX',
				9: '..XXXXXXX......XXXXXXXX.....',
				11: '..XXXXXX...XXXXX...XXXXXX...',
				13: '..XXXXXXX...XXXXX...XXXXXXX.',
			},
			11: {
				2: '...XXXXXXX...XXXXX....XXXXXX',
				4: '...XXXXXXX...XXXXX......XXXX',
				6: '...XXXXXXX....XXXXX.......XX',
				9: '...XXXXXXX.....XXXXXXXX.....',
				11: '...XXXXXXX.......XXXXXXXX...',
				13: '...XXXXXXX...XXXXX...XXXXXX.',
			},
			12: {
				2: '....XXXXXXX...XXXXX...XXXXXX',
				4: '....XXXXXXX...XXXXX.....XXXX',
				6: '....XXXXXXX...XXXXX.......XX',
				9: '....XXXXXXX....XXXXXXXX.....',
				11: '....XXXXXXX......XXXXXXXX...',
				13: '....XXXXXX...XXXXX...XXXXXX.',
			},
			13: {
				2: '.....XXXXXX...XXXXX...XXXXXX',
				4: '.....XXXXXX...XXXXX.....XXXX',
				6: '.....XXXXXX...XXXXX.......XX',
				9: '.....XXXXXXX...XXXXXXXX.....',
				11: '.....XXXXXXX.....XXXXXXXX...',
				13: '.....XXXXXXX.......XXXXXXXX.',
			},
			14: {
				2: '......XXXXX...XXXXX...XXXXXX',
				4: '......XXXXX...XXXXX.....XXXX',
				6: '......XXXXX...XXXXX.......XX',
				9: '......XXXXXX...XXXXXXXX.....',
				11: '......XXXXXXX....XXXXXXXX...',
				13: '......XXXXXXX......XXXXXXXX.',
			},
		},
	},
	B: {
		'7to7': {
			1: {
				1: 'XXXXXXX.......XXXXXXX.......',
				2: 'XXXXXXX........XXXXXXX......',
				3: 'XXXXXXX...XXXXX...XXXXX.....',
				4: 'XXXXXXX...XXXXX...XXXXXX....',
				5: 'XXXXXXX...XXXXX...XXXXXXX...',
				6: 'XXXXXXX....XXXXX...XXXXXXX..',
				7: 'XXXXXXX....XXXXXX...XXXXXXX.',
				8: 'XXXXXXX....XXXXXXX...XXXXXXX',
				9: 'XXXXXXX....XXXXXXX....XXXXXX',
				10: 'XXXXXXX....XXXXXXX.....XXXXX',
				11: 'XXXXXXX....XXXXXXX......XXXX',
				12: 'XXXXXXX....XXXXXXX.......XXX',
				13: 'XXXXXXX.....XXXXXXX.......XX',
				14: 'XXXXXXX......XXXXXXX.......X',
			},
			2: {
				1: '.XXXXXXX......XXXXXXX.......',
				2: '.XXXXXXX.......XXXXXXX......',
				3: '.XXXXXX...XXXXX...XXXXX.....',
				4: '.XXXXXXX...XXXXX...XXXXX....',
				5: '.XXXXXXX...XXXXX...XXXXXX...',
				6: '.XXXXXXX...XXXXX...XXXXXXX..',
				7: '.XXXXXXX....XXXXX...XXXXXXX.',
				8: '.XXXXXXX...XXXXXXX...XXXXXXX',
				9: '.XXXXXXX...XXXXXXX....XXXXXX',
				10: '.XXXXXXX...XXXXXXX.....XXXXX',
				11: '.XXXXXXX...XXXXXXX......XXXX',
				12: '.XXXXXXX...XXXXXXX.......XXX',
				13: '.XXXXXXX....XXXXXXX.......XX',
				14: '.XXXXXXX.....XXXXXXX.......X',
			},
			3: {
				1: '..XXXXXXX.....XXXXXXX.......',
				2: '..XXXXXXX......XXXXXXX......',
				3: '..XXXXXXX.......XXXXXXX.....',
				4: '..XXXXXX...XXXXX...XXXXX....',
				5: '..XXXXXXX...XXXXX...XXXXX...',
				6: '..XXXXXXX...XXXXX...XXXXXX..',
				7: '..XXXXXXX...XXXXX...XXXXXXX.',
				8: '..XXXXXXX...XXXXXX...XXXXXXX',
				9: '..XXXXXXX...XXXXXX....XXXXXX',
				10: '..XXXXXXX...XXXXXX.....XXXXX',
				11: '..XXXXXXX...XXXXXX......XXXX',
				12: '..XXXXXXX...XXXXXX.......XXX',
				13: '..XXXXXXX...XXXXXXX.......XX',
				14: '..XXXXXXX....XXXXXXX.......X',
			},
			4: {
				1: '...XXXXXXX....XXXXXXX.......',
				2: '...XXXXXXX.....XXXXXXX......',
				3: '...XXXXXXX......XXXXXXX.....',
				4: '...XXXXXXX.......XXXXXXX....',
				5: '...XXXXXX...XXXXX...XXXXX...',
				6: '...XXXXXXX...XXXXX...XXXXX..',
				7: '...XXXXXXX...XXXXX...XXXXXX.',
				8: '...XXXXXXX...XXXXX...XXXXXXX',
				9: '...XXXXXXX...XXXXX....XXXXXX',
				10: '...XXXXXXX...XXXXX.....XXXXX',
				11: '...XXXXXXX...XXXXX......XXXX',
				12: '...XXXXXXX...XXXXX.......XXX',
				13: '...XXXXXXX....XXXXX.......XX',
				14: '...XXXXXXX....XXXXXX.......X',
			},
			5: {
				1: '....XXXXXXX...XXXXXXX.......',
				2: '....XXXXXXX....XXXXXXX......',
				3: '....XXXXXXX.....XXXXXXX.....',
				4: '....XXXXXXX......XXXXXXX....',
				5: '....XXXXXXX.......XXXXXXX...',
				6: '....XXXXXX...XXXXX...XXXXX..',
				7: '....XXXXXX...XXXXX...XXXXXX.',
				8: '....XXXXXX...XXXXX...XXXXXXX',
				9: '....XXXXXXX...XXXXX...XXXXXX',
				10: '....XXXXXXX...XXXXX....XXXXX',
				11: '....XXXXXXX...XXXXX.....XXXX',
				12: '....XXXXXXX...XXXXX......XXX',
				13: '....XXXXXXX...XXXXX.......XX',
				14: '....XXXXXXX...XXXXXX.......X',
			},
			6: {
				1: '.....XXXXXX...XXXXXXX.......',
				2: '.....XXXXXXX...XXXXXXX......',
				3: '.....XXXXXXX....XXXXXXX.....',
				4: '.....XXXXXXX.....XXXXXXX....',
				5: '.....XXXXXXX......XXXXXXX...',
				6: '.....XXXXXXX.......XXXXXXX..',
				7: '.....XXXXX...XXXXX...XXXXXX.',
				8: '.....XXXXX...XXXXX...XXXXXXX',
				9: '.....XXXXXX...XXXXX...XXXXXX',
				10: '.....XXXXXX...XXXXX....XXXXX',
				11: '.....XXXXXX...XXXXX.....XXXX',
				12: '.....XXXXXX...XXXXX......XXX',
				13: '.....XXXXXX...XXXXX.......XX',
				14: '.....XXXXXX...XXXXXX.......X',
			},
			7: {
				1: '......XXXXX...XXXXXXX.......',
				2: '......XXXXXX...XXXXXXX......',
				3: '......XXXXXXX...XXXXXXX.....',
				4: '......XXXXXXX....XXXXXXX....',
				5: '......XXXXXXX.....XXXXXXX...',
				6: '......XXXXXXX......XXXXXXX..',
				7: '......XXXXXXX.......XXXXXXX.',
				8: '......XXXXXXX........XXXXXXX',
				9: '......XXXXX...XXXXX...XXXXXX',
				10: '......XXXXX...XXXXX....XXXXX',
				11: '......XXXXX...XXXXX.....XXXX',
				12: '......XXXXX...XXXXX......XXX',
				13: '......XXXXX...XXXXX.......XX',
				14: '......XXXXX...XXXXXX.......X',
			},
			8: {
				1: '.......XXXXXX...XXXXX.......',
				2: '.......XXXXXX...XXXXXX......',
				3: '.......XXXXXX...XXXXXXX.....',
				4: '.......XXXXXXX...XXXXXXX....',
				5: '.......XXXXXXX....XXXXXXX...',
				6: '.......XXXXXXX.....XXXXXXX..',
				7: '.......XXXXXXX......XXXXXXX.',
				8: '.......XXXXXXX.......XXXXXXX',
				9: '........XXXXXXX.......XXXXXX',
				10: '.......XXXXX...XXXXX...XXXXX',
				11: '.......XXXXX...XXXXX....XXXX',
				12: '.......XXXXXX...XXXXX....XXX',
				13: '.......XXXXXX...XXXXX.....XX',
				14: '.......XXXXXX...XXXXX......X',
			},
			9: {
				1: 'X.......XXXXX...XXXXX.......',
				2: 'X.......XXXXXX...XXXXX......',
				3: 'X........XXXXXX...XXXXX.....',
				4: 'X........XXXXXX...XXXXXX....',
				5: 'X........XXXXXX...XXXXXXX...',
				6: 'X.......XXXXXXX....XXXXXXX..',
				7: 'X........XXXXXX.....XXXXXXX.',
				8: 'X.......XXXXXXX......XXXXXXX',
				9: 'X.......XXXXXXX.......XXXXXX',
				10: 'X........XXXXXXX.......XXXXX',
				11: 'X.......XXXXX...XXXXX...XXXX',
				12: 'X.......XXXXX...XXXXX....XXX',
				13: 'X.......XXXXX...XXXXX.....XX',
				14: 'X.......XXXXX...XXXXX......X',
			},
			10: {
				1: 'XX......XXXXX...XXXXX.......',
				2: 'XX......XXXXX...XXXXXX......',
				3: 'XX.......XXXXXX...XXXXX.....',
				4: 'XX.......XXXXXX...XXXXXX....',
				5: 'XX........XXXXX...XXXXXXX...',
				6: 'XX........XXXXX....XXXXXXX..',
				7: 'XX.......XXXXXX.....XXXXXXX.',
				8: 'XX.......XXXXXXX.....XXXXXXX',
				9: 'XX.......XXXXXXX......XXXXXX',
				10: 'XX.......XXXXXXX.......XXXXX',
				11: 'XX........XXXXXXX.......XXXX',
				12: 'XX......XXXXX...XXXXX....XXX',
				13: 'XX......XXXXX...XXXXX.....XX',
				14: 'XX......XXXXX...XXXXX......X',
			},
			11: {
				1: 'XXX.....XXXXX...XXXXX.......',
				2: 'XXX.....XXXXX...XXXXXX......',
				3: 'XXX.......XXXXX...XXXXX.....',
				4: 'XXX.......XXXXX...XXXXXX....',
				5: 'XXX.......XXXXX...XXXXXXX...',
				6: 'XXX.......XXXXX....XXXXXXX..',
				7: 'XXX.......XXXXXX....XXXXXXX.',
				8: 'XXX.......XXXXXXX....XXXXXXX',
				9: 'XXX.......XXXXXXX.....XXXXXX',
				10: 'XXX.......XXXXXXX......XXXXX',
				11: 'XXX.......XXXXXXX.......XXXX',
				12: 'XXX........XXXXXXX.......XXX',
				13: 'XXX.....XXXXX...XXXXX.....XX',
				14: 'XXX.....XXXXX...XXXXX......X',
			},
			12: {
				1: 'XXXX....XXXXX...XXXXX.......',
				2: 'XXXX....XXXXX...XXXXXX......',
				3: 'XXXX....XXXXX...XXXXXXX.....',
				4: 'XXXX......XXXXX...XXXXXX....',
				5: 'XXXX......XXXXX...XXXXXXX...',
				6: 'XXXX.......XXXXX...XXXXXXX..',
				7: 'XXXX.......XXXXXX...XXXXXXX.',
				8: 'XXXX......XXXXXXX....XXXXXXX',
				9: 'XXXX.......XXXXXXX....XXXXXX',
				10: 'XXXX.......XXXXXXX.....XXXXX',
				11: 'XXXX.......XXXXXXX......XXXX',
				12: 'XXXX.......XXXXXXX.......XXX',
				13: 'XXXX....XXXXX...XXXXX.....XX',
				14: 'XXXX....XXXXX...XXXXX......X',
			},
			13: {
				1: 'XXXXX...XXXXX...XXXXX.......',
				2: 'XXXXX....XXXXX...XXXXX......',
				3: 'XXXXX.....XXXXX...XXXXX.....',
				4: 'XXXXX.....XXXXX...XXXXXX....',
				5: 'XXXXX.....XXXXX...XXXXXXX...',
				6: 'XXXXX......XXXXX...XXXXXXX..',
				7: 'XXXXX......XXXXXX...XXXXXXX.',
				8: 'XXXXX.....XXXXXXX....XXXXXXX',
				9: 'XXXXX......XXXXXXX....XXXXXX',
				10: 'XXXXX......XXXXXXX.....XXXXX',
				11: 'XXXXX......XXXXXXX......XXXX',
				12: 'XXXXX......XXXXXXX.......XXX',
				13: 'XXXXX.......XXXXXXX.......XX',
				14: 'XXXXX.......XXXXXXX........X',
			},
			14: {
				1: 'XXXXXX.......XXXXXXX........',
				2: 'XXXXXX...XXXXX...XXXXX......',
				3: 'XXXXXX....XXXXX...XXXXX.....',
				4: 'XXXXXX....XXXXX...XXXXXX....',
				5: 'XXXXXX....XXXXX...XXXXXXX...',
				6: 'XXXXXX.....XXXXX...XXXXXXX..',
				7: 'XXXXXX.....XXXXXX...XXXXXXX.',
				8: 'XXXXXX....XXXXXXX....XXXXXXX',
				9: 'XXXXXX.....XXXXXXX....XXXXXX',
				10: 'XXXXXX.....XXXXXXX.....XXXXX',
				11: 'XXXXXX.....XXXXXXX......XXXX',
				12: 'XXXXXX.....XXXXXXX.......XXX',
				13: 'XXXXXX......XXXXXXX.......XX',
				14: 'XXXXXX.......XXXXXXX.......X',
			},
		},
		'8to8': {
			2: {
				2: '.XXXXXXXX......XXXXXXXX.....',
				4: '.XXXXXXX...XXXXX...XXXXXX...',
				6: '.XXXXXXX...XXXXX...XXXXXXXX.',
				9: '.XXXXXXX...XXXXXXX....XXXXXX',
				11: '.XXXXXXX...XXXXXXXX.....XXXX',
				13: '.XXXXXXX....XXXXXXXX......XX',
			},
			4: {
				2: '...XXXXXXXX....XXXXXXXX.....',
				4: '...XXXXXXXX......XXXXXXXX...',
				6: '...XXXXXXX...XXXXX...XXXXXX.',
				9: '...XXXXXXX...XXXXX....XXXXXX',
				11: '...XXXXXXX...XXXXX......XXXX',
				13: '...XXXXXXXX...XXXXX.......XX',
			},
			6: {
				2: '.....XXXXXXX...XXXXXXXX.....',
				4: '.....XXXXXXXX....XXXXXXXX...',
				6: '.....XXXXXXXX......XXXXXXXX.',
				9: '.....XXXXXX...XXXXX...XXXXXX',
				11: '.....XXXXXX...XXXXXX....XXXX',
				13: '.....XXXXXX...XXXXXX......XX',
			},
			9: {
				2: 'XX.....XXXXXXX...XXXXXX.....',
				4: 'XX......XXXXXXX...XXXXXXX...',
				6: 'XX......XXXXXXXX...XXXXXXXX.',
				9: 'XX......XXXXXXXX......XXXXXX',
				11: 'XX.....XXXXXX...XXXXX...XXXX',
				13: 'XX.....XXXXXX...XXXXX.....XX',
			},
			11: {
				2: 'XXXX....XXXXX...XXXXXXX.....',
				4: 'XXXX......XXXXX...XXXXXXX...',
				6: 'XXXX......XXXXX....XXXXXXXX.',
				9: 'XXXX......XXXXXXXX....XXXXXX',
				11: 'XXXX......XXXXXXXX......XXXX',
				13: 'XXXX....XXXXX...XXXXX.....XX',
			},
			13: {
				2: 'XXXXXX...XXXXX...XXXXXX.....',
				4: 'XXXXXX...XXXXXX...XXXXXXX...',
				6: 'XXXXXX....XXXXXX...XXXXXXXX.',
				9: 'XXXXXX....XXXXXXXX....XXXXXX',
				11: 'XXXXXX.....XXXXXXXX.....XXXX',
				13: 'XXXXXX......XXXXXXXX......XX',
			},
		},
		'8to7': {
			2: {
				1: '.XXXXXXXX.....XXXXXXX.......',
				2: '.XXXXXXXX......XXXXXXX......',
				3: '.XXXXXX...XXXXX...XXXXX.....',
				4: '.XXXXXXX...XXXXX...XXXXX....',
				5: '.XXXXXXX...XXXXX...XXXXXX...',
				6: '.XXXXXXX...XXXXX...XXXXXXX..',
				7: '.XXXXXXXX...XXXXX...XXXXXXX.',
				8: '.XXXXXXX...XXXXXXX...XXXXXXX',
				9: '.XXXXXXX...XXXXXXXX...XXXXXX',
				10: '.XXXXXXX...XXXXXXXX....XXXXX',
				11: '.XXXXXXX...XXXXXXXX.....XXXX',
				12: '.XXXXXXX...XXXXXXXX......XXX',
				13: '.XXXXXXX....XXXXXXXX......XX',
				14: '.XXXXXXX.....XXXXXXXX......X',
			},
			4: {
				1: '...XXXXXXXX...XXXXXXX.......',
				2: '...XXXXXXXX....XXXXXXX......',
				3: '...XXXXXXXX.....XXXXXXX.....',
				4: '...XXXXXXXX......XXXXXXX....',
				5: '...XXXXXX...XXXXX...XXXXX...',
				6: '...XXXXXXX...XXXXX...XXXXX..',
				7: '...XXXXXXX...XXXXX...XXXXXX.',
				8: '...XXXXXXX...XXXXX...XXXXXXX',
				9: '...XXXXXXX...XXXXX....XXXXXX',
				10: '...XXXXXXX...XXXXX.....XXXXX',
				11: '...XXXXXXX...XXXXX......XXXX',
				12: '...XXXXXXX...XXXXX.......XXX',
				13: '...XXXXXXXX...XXXXX.......XX',
				14: '...XXXXXXXX...XXXXXX.......X',
			},
			6: {
				1: '.....XXXXXX...XXXXXXX.......',
				2: '.....XXXXXXX...XXXXXXX......',
				3: '.....XXXXXXXX...XXXXXXX.....',
				4: '.....XXXXXXXX....XXXXXXX....',
				5: '.....XXXXXXXX.....XXXXXXX...',
				6: '.....XXXXXXXX......XXXXXXX..',
				7: '.....XXXXX...XXXXX...XXXXXX.',
				8: '.....XXXXX...XXXXX...XXXXXXX',
				9: '.....XXXXXX...XXXXX...XXXXXX',
				10: '.....XXXXXX...XXXXXX...XXXXX',
				11: '.....XXXXXX...XXXXXX....XXXX',
				12: '.....XXXXXX...XXXXXX.....XXX',
				13: '.....XXXXXX...XXXXXX......XX',
				14: '.....XXXXXX...XXXXXXX......X',
			},
			9: {
				1: 'XX.....XXXXXX...XXXXX.......',
				2: 'XX.....XXXXXXX...XXXXX......',
				3: 'XX......XXXXXXX...XXXXX.....',
				4: 'XX......XXXXXXX...XXXXXX....',
				5: 'XX......XXXXXXX...XXXXXXX...',
				6: 'XX......XXXXXXXX...XXXXXXX..',
				7: 'XX......XXXXXXX.....XXXXXXX.',
				8: 'XX......XXXXXXXX.....XXXXXXX',
				9: 'XX......XXXXXXXX......XXXXXX',
				10: 'XX.......XXXXXXXX......XXXXX',
				11: 'XX.....XXXXXX...XXXXX...XXXX',
				12: 'XX.....XXXXXX...XXXXX....XXX',
				13: 'XX.....XXXXXX...XXXXX.....XX',
				14: 'XX.....XXXXXX...XXXXX......X',
			},
			11: {
				1: 'XXXX....XXXXX...XXXXX.......',
				2: 'XXXX....XXXXX...XXXXXX......',
				3: 'XXXX......XXXXX...XXXXX.....',
				4: 'XXXX......XXXXX...XXXXXX....',
				5: 'XXXX......XXXXX...XXXXXXX...',
				6: 'XXXX......XXXXX....XXXXXXX..',
				7: 'XXXX......XXXXXX....XXXXXXX.',
				8: 'XXXX......XXXXXXXX...XXXXXXX',
				9: 'XXXX......XXXXXXXX....XXXXXX',
				10: 'XXXX......XXXXXXXX.....XXXXX',
				11: 'XXXX......XXXXXXXX......XXXX',
				12: 'XXXX.......XXXXXXXX......XXX',
				13: 'XXXX....XXXXX...XXXXX.....XX',
				14: 'XXXX....XXXXX...XXXXX......X',
			},
			13: {
				1: 'XXXXXX...XXXX...XXXXX.......',
				2: 'XXXXXX...XXXXX...XXXXX......',
				3: 'XXXXXX...XXXXXX...XXXXX.....',
				4: 'XXXXXX...XXXXXX...XXXXXX....',
				5: 'XXXXXX...XXXXXX...XXXXXXX...',
				6: 'XXXXXX....XXXXXX...XXXXXXX..',
				7: 'XXXXXX....XXXXXXX...XXXXXXX.',
				8: 'XXXXXX....XXXXXXXX...XXXXXXX',
				9: 'XXXXXX.....XXXXXXXX...XXXXXX',
				10: 'XXXXXX.....XXXXXXXX....XXXXX',
				11: 'XXXXXX.....XXXXXXXX.....XXXX',
				12: 'XXXXXX.....XXXXXXXX......XXX',
				13: 'XXXXXX......XXXXXXXX......XX',
				14: 'XXXXXX......XXXXXXXX.......X',
			},
		},
		'7to8': {
			1: {
				2: 'XXXXXXX........XXXXXXXX.....',
				4: 'XXXXXXX...XXXXX...XXXXXXX...',
				6: 'XXXXXXX....XXXXX...XXXXXXXX.',
				9: 'XXXXXXX....XXXXXXX....XXXXXX',
				11: 'XXXXXXX....XXXXXXX......XXXX',
				13: 'XXXXXXX.....XXXXXXX.......XX',
			},
			2: {
				2: '.XXXXXXX.......XXXXXXXX.....',
				4: '.XXXXXXX...XXXXX...XXXXXX...',
				6: '.XXXXXXX...XXXXX...XXXXXXXX.',
				9: '.XXXXXXX...XXXXXXX....XXXXXX',
				11: '.XXXXXXX...XXXXXXX......XXXX',
				13: '.XXXXXXX....XXXXXXX.......XX',
			},
			3: {
				2: '..XXXXXXX......XXXXXXXX.....',
				4: '..XXXXXX...XXXXX...XXXXXX...',
				6: '..XXXXXXX...XXXXX...XXXXXXX.',
				9: '..XXXXXXX...XXXXXX....XXXXXX',
				11: '..XXXXXXX...XXXXXX......XXXX',
				13: '..XXXXXXX...XXXXXXX.......XX',
			},
			4: {
				2: '...XXXXXXX.....XXXXXXXX.....',
				4: '...XXXXXXX.......XXXXXXXX...',
				6: '...XXXXXXX...XXXXX...XXXXXX.',
				9: '...XXXXXXX...XXXXX....XXXXXX',
				11: '...XXXXXXX...XXXXX......XXXX',
				13: '...XXXXXXX....XXXXX.......XX',
			},
			5: {
				2: '....XXXXXXX....XXXXXXXX.....',
				4: '....XXXXXXX......XXXXXXXX...',
				6: '....XXXXXX...XXXXX...XXXXXX.',
				9: '....XXXXXXX...XXXXX...XXXXXX',
				11: '....XXXXXXX...XXXXX.....XXXX',
				13: '....XXXXXXX...XXXXX.......XX',
			},
			6: {
				2: '.....XXXXXXX...XXXXXXXX.....',
				4: '.....XXXXXXX.....XXXXXXXX...',
				6: '.....XXXXXXX.......XXXXXXXX.',
				9: '.....XXXXXX...XXXXX...XXXXXX',
				11: '.....XXXXXX...XXXXX.....XXXX',
				13: '.....XXXXXX...XXXXX.......XX',
			},
			7: {
				2: '......XXXXXX...XXXXXXXX.....',
				4: '......XXXXXXX....XXXXXXXX...',
				6: '......XXXXXXX......XXXXXXXX.',
				9: '......XXXXX...XXXXX...XXXXXX',
				11: '......XXXXX...XXXXX.....XXXX',
				13: '......XXXXX...XXXXX.......XX',
			},
			8: {
				2: '.......XXXXXX...XXXXXXX.....',
				4: '.......XXXXXXX...XXXXXXXX...',
				6: '.......XXXXXXX.....XXXXXXXX.',
				9: '........XXXXXXX.......XXXXXX',
				11: '.......XXXXX...XXXXX....XXXX',
				13: '.......XXXXXX...XXXXX.....XX',
			},
			9: {
				2: 'X.......XXXXXX...XXXXXX.....',
				4: 'X........XXXXXX...XXXXXXX...',
				6: 'X.......XXXXXXX....XXXXXXXX.',
				9: 'X.......XXXXXXX.......XXXXXX',
				11: 'X.......XXXXX...XXXXX...XXXX',
				13: 'X.......XXXXX...XXXXX.....XX',
			},
			10: {
				2: 'XX......XXXXX...XXXXXXX.....',
				4: 'XX.......XXXXXX...XXXXXXX...',
				6: 'XX........XXXXX....XXXXXXXX.',
				9: 'XX.......XXXXXXX......XXXXXX',
				11: 'XX........XXXXXXX.......XXXX',
				13: 'XX......XXXXX...XXXXX.....XX',
			},
			11: {
				2: 'XXX.....XXXXX...XXXXXXX.....',
				4: 'XXX.......XXXXX...XXXXXXX...',
				6: 'XXX.......XXXXX....XXXXXXXX.',
				9: 'XXX.......XXXXXXX.....XXXXXX',
				11: 'XXX.......XXXXXXX.......XXXX',
				13: 'XXX.....XXXXX...XXXXX.....XX',
			},
			12: {
				2: 'XXXX....XXXXX...XXXXXXX.....',
				4: 'XXXX......XXXXX...XXXXXXX...',
				6: 'XXXX.......XXXXX...XXXXXXXX.',
				9: 'XXXX.......XXXXXXX....XXXXXX',
				11: 'XXXX.......XXXXXXX......XXXX',
				13: 'XXXX....XXXXX...XXXXX.....XX',
			},
			13: {
				2: 'XXXXX....XXXXX...XXXXXX.....',
				4: 'XXXXX.....XXXXX...XXXXXXX...',
				6: 'XXXXX......XXXXX...XXXXXXXX.',
				9: 'XXXXX......XXXXXXX....XXXXXX',
				11: 'XXXXX......XXXXXXX......XXXX',
				13: 'XXXXX.......XXXXXXX.......XX',
			},
			14: {
				2: 'XXXXXX...XXXXX...XXXXXX.....',
				4: 'XXXXXX....XXXXX...XXXXXXX...',
				6: 'XXXXXX.....XXXXX...XXXXXXXX.',
				9: 'XXXXXX.....XXXXXXX....XXXXXX',
				11: 'XXXXXX.....XXXXXXX......XXXX',
				13: 'XXXXXX......XXXXXXX.......XX',
			},
		},
	},
};
