<script lang="ts">
  import FAA8710ClassHours from '$lib/components/routeSpecific/reports/FAA8710ClassHours.svelte';
  import FAA8710Row from '$lib/components/routeSpecific/reports/FAA8710Row.svelte';
  import FAA8710RowSim from '$lib/components/routeSpecific/reports/FAA8710RowSim.svelte';
  import { timeConverter } from '$lib/helpers';


  export let data: import('./$types').PageData;

  const now = (new Date);


</script>

<div class="m-6 flex flex-col lg:flex-row gap-6 print:hidden">
  <div class="grow flex flex-col gap-0">
    <div class="uppercase text-center text-base md:text-xs font-normal mb-1">Summary</div>
    <div class="grow flex flex-col divide-y gap-2 bg-gray-50 pb-[7px] dark:bg-zinc-900 shadow-sm ring-1 ring-gray-900/5 dark:ring-zinc-700">
      <div class="flex flex-row gap-6 mt-4 pb-2">
        <div class="flex-auto pl-6">
          <dt class="text-sm font-semibold leading-6 text-gray-900 dark:text-zinc-50">Total Hours</dt>
          <dd class="mt-1 text-base font-semibold font-mono leading-6 text-gray-900 dark:text-zinc-50">{data.total.toFixed(1)} hours</dd>
        </div>
        <div class="flex-auto pl-6">
          <dt class="text-sm font-semibold leading-6 text-gray-900 dark:text-zinc-50">Total Legs</dt>
          <dd class="mt-1 text-base font-semibold font-mono leading-6 text-gray-900 dark:text-zinc-50">{data.legs}</dd>
        </div>
      </div>
      <div class="grow flex flex-col gap-4 mb-2">
        <div class="flex w-full flex-grow gap-x-4 px-6 pt-6">
          <dt class="flex-none">
            <span class="sr-only">Client</span>
            <img class="h-5 w-5 rounded-full" src="https://www.gravatar.com/avatar/{data.settings["general.gravatar.hash"]}?s=300&d=identicon" alt="">
          </dt>
          <dd class="text-sm font-medium leading-6 text-gray-900 dark:text-zinc-50">{data.name}</dd>
        </div>
        <div class="flex w-full flex-grow gap-x-4 px-6">
          <dt class="flex-none">
            <span class="sr-only">Date Generated</span>
            <svg class="h-6 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M5.25 12a.75.75 0 01.75-.75h.01a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75H6a.75.75 0 01-.75-.75V12zM6 13.25a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75h.01a.75.75 0 00.75-.75V14a.75.75 0 00-.75-.75H6zM7.25 12a.75.75 0 01.75-.75h.01a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75H8a.75.75 0 01-.75-.75V12zM8 13.25a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75h.01a.75.75 0 00.75-.75V14a.75.75 0 00-.75-.75H8zM9.25 10a.75.75 0 01.75-.75h.01a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75H10a.75.75 0 01-.75-.75V10zM10 11.25a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75h.01a.75.75 0 00.75-.75V12a.75.75 0 00-.75-.75H10zM9.25 14a.75.75 0 01.75-.75h.01a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75H10a.75.75 0 01-.75-.75V14zM12 9.25a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75h.01a.75.75 0 00.75-.75V10a.75.75 0 00-.75-.75H12zM11.25 12a.75.75 0 01.75-.75h.01a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75H12a.75.75 0 01-.75-.75V12zM12 13.25a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75h.01a.75.75 0 00.75-.75V14a.75.75 0 00-.75-.75H12zM13.25 10a.75.75 0 01.75-.75h.01a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75H14a.75.75 0 01-.75-.75V10zM14 11.25a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75h.01a.75.75 0 00.75-.75V12a.75.75 0 00-.75-.75H14z" />
              <path fill-rule="evenodd" d="M5.75 2a.75.75 0 01.75.75V4h7V2.75a.75.75 0 011.5 0V4h.25A2.75 2.75 0 0118 6.75v8.5A2.75 2.75 0 0115.25 18H4.75A2.75 2.75 0 012 15.25v-8.5A2.75 2.75 0 014.75 4H5V2.75A.75.75 0 015.75 2zm-1 5.5c-.69 0-1.25.56-1.25 1.25v6.5c0 .69.56 1.25 1.25 1.25h10.5c.69 0 1.25-.56 1.25-1.25v-6.5c0-.69-.56-1.25-1.25-1.25H4.75z" clip-rule="evenodd" />
            </svg>
          </dt>
          <dd class="text-sm leading-6 text-gray-500 dark:text-zinc-500">
            <time datetime="2023-01-31">{timeConverter(now.getTime() / 1000)}</time>
          </dd>
        </div>
        <div class="flex w-full flex-grow gap-x-4 px-6">
          <dt class="flex-none">
            <span class="sr-only">Status</span>
            <img class="w-5" src="/logo-inverted.png" alt="Contour">
          </dt>
          <dd class="text-sm leading-6 text-gray-500 dark:text-zinc-500">Generated by Contour</dd>
        </div>
      </div>
      <div class="px-6 py-6">
        <button on:click={() => window.print()} class="text-sm font-semibold leading-6 text-gray-900 dark:text-zinc-50 group">
          Print 8710 <span class="transition-padding group-hover:pl-1" aria-hidden="true">&rarr;</span>
        </button>
      </div>
    </div>
  </div>
  <div class="flex-grow">
    <div class="uppercase text-center text-base md:text-xs font-normal mb-1">Class Hours</div>
    <FAA8710ClassHours data={data.classHours} />
  </div>
</div>

<hr />
<div class="relative p-6 pt-3 px-0 mb-8 print:p-1 m-0 print:-mx-2 print:mt-4">
  <div class="uppercase text-center text-base md:text-xs font-normal mb-1 print:text-lg print:md:text-lg">Generated 8710</div>
  <div class="p-1 pb-6 print:p-1 w-full overflow-x-scroll touch-auto lg:overflow-x-hidden relative">
    <div class="grid grid-cols-13 min-w-[1000px] lg:min-w-full relative pr-6">
      <!-- Column Titles -->
      <div class="text-xxs xl:text-xs select-none content-end text-center uppercase mb-2"></div>
      <div class="text-xxs xl:text-xs select-none content-end text-center uppercase mb-2">Total</div>
      <div class="text-xxs xl:text-xs select-none content-end text-center uppercase mb-2">Dual Received</div>
      <div class="text-xxs xl:text-xs select-none content-end text-center uppercase mb-2">Solo</div>
      <div class="text-xxs xl:text-xs select-none content-end text-center uppercase mb-2">PIC & SIC</div>
      <div class="text-xxs xl:text-xs select-none content-end text-center uppercase mb-2">XC Dual Received</div>
      <div class="text-xxs xl:text-xs select-none content-end text-center uppercase mb-2">XC Solo</div>
      <div class="text-xxs xl:text-xs select-none content-end text-center uppercase mb-2">XC <span class="whitespace-nowrap">PIC / SIC</span></div>
      <div class="text-xxs xl:text-xs select-none content-end text-center uppercase mb-2">Inst.</div>
      <div class="text-xxs xl:text-xs select-none content-end text-center uppercase mb-2">Night Dual Received</div>
      <div class="text-xxs xl:text-xs select-none content-end text-center uppercase mb-2">Night TOL</div>
      <div class="text-xxs xl:text-xs select-none content-end text-center uppercase mb-2">Night <span class="whitespace-nowrap">PIC / SIC</span></div>
      <div class="text-xxs xl:text-xs select-none content-end text-center uppercase mb-2">Night TOL <span class="whitespace-nowrap">PIC / SIC</span></div>

      <!-- Row Titles -->
      <div class="row-start-3 text-xxs xl:text-xs uppercase inline-flex items-center justify-center select-none">
        <div class="-rotate-45">R.C.</div>
      </div>
      <div class="row-start-2 text-xxs xl:text-xs uppercase inline-flex items-center justify-center select-none">
        <div class="-rotate-45">Airplane</div>
      </div>
      <div class="row-start-4 text-xxs xl:text-xs uppercase inline-flex items-center justify-center select-none">
        <div class="-rotate-45">P.L.</div>
      </div>
      <div class="row-start-5 text-xxs xl:text-xs uppercase inline-flex items-center justify-center select-none">
        <div class="-rotate-45">Gliders</div>
      </div>
      <div class="row-start-6 text-xxs xl:text-xs uppercase inline-flex items-center justify-center select-none">
        <div class="-rotate-45">L.T.A.</div>
      </div>
      <div class="row-start-7 text-xxs xl:text-xs uppercase inline-flex items-center justify-center select-none">
        <div class="-rotate-45">FFS</div>
      </div>
      <div class="row-start-8 text-xxs xl:text-xs uppercase inline-flex items-center justify-center select-none">
        <div class="-rotate-45">FTD</div>
      </div>
      <div class="row-start-9 text-xxs xl:text-xs uppercase inline-flex items-center justify-center select-none">
        <div class="-rotate-45">ATD</div>
      </div>

      <div class="print-color-adjust-exact col-span-12 col-start-2 row-span-8 grid grid-cols-12 grid-rows-subgrid text-xs text-center shadow-sm ring-1 ring-gray-900/5 dark:ring-zinc-700 relative">
        <div class="absolute -z-10 top-0 bottom-0 left-0 right-0 bg-hashLight dark:bg-hashDark dark:opacity-50"/>
        <!-- Rows -->
        <FAA8710Row class="bg-zinc-50 dark:bg-zinc-900" data={data.airplane} title="Airplane" />
        <FAA8710Row class="bg-zinc-100 dark:bg-zinc-925" data={data.rc} title="R.C." />
        <FAA8710Row class="bg-zinc-50 dark:bg-zinc-900" data={data.pl} title="P.L." />
        <FAA8710Row class="bg-zinc-100 dark:bg-zinc-925" data={data.glider} title="Gliders" />
        <FAA8710Row class="bg-zinc-50 dark:bg-zinc-900" data={data.lta} title="L.T.A." />
        <FAA8710RowSim class="bg-zinc-100 dark:bg-zinc-925" data={data.ffs} title="FFS" />
        <FAA8710RowSim class="bg-zinc-50 dark:bg-zinc-900" data={data.ftd} title="FTD" />
        <FAA8710RowSim class="bg-zinc-100 dark:bg-zinc-925" data={data.atd} title="ATD" last={true} />

      </div>
    </div>
  </div>
</div>

<div class="hidden print:flex flex-r items-center justify-center gap-1">
  <div class="flex flex-grow gap-x-4 justify-center">
    <dt class="flex-none">
      <span class="sr-only">Client</span>
      <img class="h-5 w-5 rounded-full" src="https://www.gravatar.com/avatar/{data.settings["general.gravatar.hash"]}?s=300&d=identicon" alt="">
    </dt>
    <dd class="text-sm font-medium leading-6 text-gray-900 dark:text-zinc-50">{data.name}</dd>
  </div>
  <div class="flex flex-grow gap-x-4 justify-center">
    <dt class="flex-none">
      <span class="sr-only">Date Generated</span>
      <svg class="h-6 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path d="M5.25 12a.75.75 0 01.75-.75h.01a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75H6a.75.75 0 01-.75-.75V12zM6 13.25a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75h.01a.75.75 0 00.75-.75V14a.75.75 0 00-.75-.75H6zM7.25 12a.75.75 0 01.75-.75h.01a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75H8a.75.75 0 01-.75-.75V12zM8 13.25a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75h.01a.75.75 0 00.75-.75V14a.75.75 0 00-.75-.75H8zM9.25 10a.75.75 0 01.75-.75h.01a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75H10a.75.75 0 01-.75-.75V10zM10 11.25a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75h.01a.75.75 0 00.75-.75V12a.75.75 0 00-.75-.75H10zM9.25 14a.75.75 0 01.75-.75h.01a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75H10a.75.75 0 01-.75-.75V14zM12 9.25a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75h.01a.75.75 0 00.75-.75V10a.75.75 0 00-.75-.75H12zM11.25 12a.75.75 0 01.75-.75h.01a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75H12a.75.75 0 01-.75-.75V12zM12 13.25a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75h.01a.75.75 0 00.75-.75V14a.75.75 0 00-.75-.75H12zM13.25 10a.75.75 0 01.75-.75h.01a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75H14a.75.75 0 01-.75-.75V10zM14 11.25a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75h.01a.75.75 0 00.75-.75V12a.75.75 0 00-.75-.75H14z" />
        <path fill-rule="evenodd" d="M5.75 2a.75.75 0 01.75.75V4h7V2.75a.75.75 0 011.5 0V4h.25A2.75 2.75 0 0118 6.75v8.5A2.75 2.75 0 0115.25 18H4.75A2.75 2.75 0 012 15.25v-8.5A2.75 2.75 0 014.75 4H5V2.75A.75.75 0 015.75 2zm-1 5.5c-.69 0-1.25.56-1.25 1.25v6.5c0 .69.56 1.25 1.25 1.25h10.5c.69 0 1.25-.56 1.25-1.25v-6.5c0-.69-.56-1.25-1.25-1.25H4.75z" clip-rule="evenodd" />
      </svg>
    </dt>
    <dd class="text-sm leading-6 text-gray-500 dark:text-zinc-500">
      <time datetime="2023-01-31">{timeConverter(now.getTime() / 1000)}</time>
    </dd>
  </div>
  <div class="flex flex-grow gap-x-4 justify-center">
    <dt class="flex-none">
      <span class="sr-only">Status</span>
      <img class="w-5" src="/logo-inverted.png" alt="Contour">
    </dt>
    <dd class="text-sm leading-6 text-gray-500 dark:text-zinc-500">Generated by Contour</dd>
  </div>
</div>

<div class="hidden print:block fixed bottom-0 left-4 text-xxs">Verify that values match FAA requirements.</div>